import assert from 'node:assert/strict';
import { mkdtemp, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { startLocalReviewPreview } from './reviews-dev.mjs';
import { projectRoot } from './build-site.mjs';

await mkdir(join(projectRoot, '.local'), { recursive: true });
const directory = await mkdtemp(join(projectRoot, '.local/reviews-e2e-'));
const preview = await startLocalReviewPreview({ port: 0, directory });
const browser = await chromium.launch({ headless: true, ...(process.env.REVIEWS_BROWSER_PATH ? { executablePath: process.env.REVIEWS_BROWSER_PATH } : process.platform === 'win32' ? { channel: 'msedge' } : {}) });
const errors = [];
try {
  const guest = await browser.newPage(); const admin = await browser.newPage();
  for (const page of [guest, admin]) {
    page.on('pageerror', error => errors.push(error.message));
    // The feature should work even when fonts, analytics and other third-party assets are unavailable.
    await page.route('**/*', route => new URL(route.request().url()).origin === preview.url ? route.continue() : route.abort());
  }
  const submittedPhotoCounts = [];
  await guest.route(preview.url + '/reviews-api/submit', async route => {
    const request = route.request();
    const form = await new Request(request.url(), { method: 'POST', headers: request.headers(), body: request.postDataBuffer() }).formData();
    submittedPhotoCounts.push(form.getAll('photos').length);
    await route.continue();
  });
  await guest.goto(preview.url, { waitUntil: 'domcontentloaded' });
  await guest.locator('#open-feedback-btn').click();
  await guest.locator('[name=name]').fill('Viajera de prueba');
  await guest.locator('[name=rating][value="1"]').check();
  await guest.locator('[name=comment]').fill('El recorrido fue interesante pero el transporte llegó tarde.');
  await guest.locator('[name=consent]').check();
  await guest.locator('#feedback-form button[type=submit]').click();
  await guest.waitForFunction(() => document.querySelector('#feedback-form-success').textContent.includes('pendiente'));
  assert.equal(await guest.locator('#feedback-modal').getAttribute('aria-hidden'), 'true', 'Saved review must close the form');
  assert.equal(await guest.locator('#feedback-form-success').isVisible(), true, 'Confirmation must remain visible on the page');
  assert.equal(submittedPhotoCounts[0], 0, 'Text-only reviews must omit the empty browser file entry');
  assert.equal(await guest.locator('.testimonial-author-name').count(), 0, 'Pending review must remain invisible');

  await admin.goto(preview.url + '/admin/', { waitUntil: 'domcontentloaded' });
  await admin.locator('.admin-header img').evaluate(image => image.decode());
  assert.ok(await admin.locator('.admin-header img').evaluate(image => image.naturalWidth > 0), 'Admin logo must load');
  await admin.locator('[name=email]').fill('pruebas@local.invalid');
  await admin.locator('#login-form [name=password]').fill('resenas-local');
  await admin.locator('#login-form button[type=submit]').click();
  await admin.locator('.admin-review').waitFor();
  assert.equal(await admin.locator('.admin-review h3').textContent(), 'Viajera de prueba');
  admin.on('dialog', dialog => dialog.accept());
  await admin.locator('.admin-review').getByRole('button', { name: 'Publicar', exact: true }).click();
  await admin.waitForFunction(() => document.querySelector('#admin-message').textContent.includes('publicada'));
  await guest.reload({ waitUntil: 'domcontentloaded' });
  await guest.locator('.testimonial-author-name').waitFor();
  assert.equal(await guest.locator('.testimonial-author-name').textContent(), 'Viajera de prueba');

  await guest.locator('#open-feedback-btn').click();
  await guest.locator('[name=name]').fill('Prueba de texto seguro');
  await guest.locator('[name=rating][value="3"]').check();
  const html = '<img src=x onerror="window.reviewAttack=1"> Esta crítica debe aparecer como texto.';
  await guest.locator('[name=comment]').fill(html); await guest.locator('[name=consent]').check();
  await guest.locator('#feedback-form button[type=submit]').click();
  await guest.waitForFunction(() => document.querySelector('#feedback-form-success').textContent.includes('pendiente'));
  await admin.locator('#reload').click();
  await admin.locator('.admin-review').filter({ hasText: 'Prueba de texto seguro' }).waitFor();
  assert.equal(await admin.locator('.review-body img').count(), 0);
  await admin.locator('.admin-review').filter({ hasText: 'Prueba de texto seguro' }).getByRole('button', { name: 'Publicar', exact: true }).click();
  await admin.waitForFunction(() => document.querySelector('#review-list').textContent.includes('No hay reseñas'));
  await guest.reload({ waitUntil: 'domcontentloaded' });
  await guest.locator('.testimonial-author-name').filter({ hasText: 'Prueba de texto seguro' }).waitFor();
  assert.equal(await guest.locator('.testimonial-comment img').count(), 0);
  assert.equal(await guest.evaluate(() => window.reviewAttack), undefined);

  await admin.locator('#manual-mode').check();
  await admin.waitForFunction(() => document.querySelector('#admin-message').textContent.includes('revisión manual'));
  await guest.locator('#open-feedback-btn').click();
  await guest.locator('[name=name]').fill('Viajero con foto');
  await guest.locator('[name=rating][value="5"]').check();
  await guest.locator('[name=comment]').fill('La visita fue una experiencia agradable y pude tomar esta foto.');
  await guest.locator('[name=photos]').setInputFiles({ name: 'foto.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aQioAAAAASUVORK5CYII=', 'base64') });
  await guest.locator('[name=consent]').check(); await guest.locator('#feedback-form button[type=submit]').click();
  await guest.waitForFunction(() => document.querySelector('#feedback-form-success').textContent.includes('pendiente'));
  const publicBefore = await (await fetch(preview.url + '/reviews-api/public')).json();
  assert.equal(submittedPhotoCounts[2], 1, 'An attached photo must still be submitted');
  assert.equal(publicBefore.reviews.some(review => review.author.name === 'Viajero con foto'), false);
  await admin.locator('#reload').click();
  const photoCard = admin.locator('.admin-review').filter({ hasText: 'Viajero con foto' }); await photoCard.waitFor();
  assert.equal(await photoCard.locator('img').count(), 1);
  const signed = await photoCard.locator('img').getAttribute('src');
  assert.equal((await fetch(signed)).status, 200);
  assert.equal((await fetch(signed.split('?')[0])).status, 403);
  await photoCard.getByRole('button', { name: 'Publicar', exact: true }).click();
  await admin.waitForFunction(() => document.querySelector('#review-list').textContent.includes('No hay reseñas'));
  await guest.reload({ waitUntil: 'domcontentloaded' });
  await guest.locator('.testimonial-author-name').filter({ hasText: 'Viajero con foto' }).waitFor();
  assert.equal((await (await fetch(preview.url + '/reviews-api/public')).json()).reviews[0].photos.length, 1);

  await guest.locator('#open-feedback-btn').click();
  await guest.locator('[name=name]').fill('Prueba de límite');
  await guest.locator('[name=rating][value="4"]').check();
  await guest.locator('[name=comment]').fill('Este cuarto envío debe conservar el comentario y mostrar el límite.');
  await guest.locator('[name=consent]').check(); await guest.locator('#feedback-form button[type=submit]').click();
  await guest.waitForFunction(() => document.querySelector('#feedback-form-error').textContent.includes('diez minutos'));
  assert.equal(await guest.locator('[name=comment]').inputValue(), 'Este cuarto envío debe conservar el comentario y mostrar el límite.');
  assert.equal(await guest.locator('#feedback-form-success').isVisible(), false);
  assert.equal(await guest.locator('#feedback-modal').getAttribute('aria-hidden'), 'false', 'Failed submission must preserve the open form');

  await admin.locator('#status-filter').selectOption('approved');
  await admin.locator('.admin-review').filter({ hasText: 'Viajera de prueba' }).waitFor();
  await admin.locator('.admin-review').filter({ hasText: 'Viajera de prueba' }).getByRole('button', { name: 'Ocultar', exact: true }).click();
  await admin.waitForFunction(() => !document.querySelector('#review-list').textContent.includes('Viajera de prueba'));
  assert.equal((await (await fetch(preview.url + '/reviews-api/public')).json()).reviews.some(review => review.author.name === 'Viajera de prueba'), false);
  await guest.locator('#close-feedback-btn').click();
  await guest.evaluate(() => window.__estI18n.setLang('pt'));
  await guest.locator('#open-feedback-btn').click();
  assert.equal(await guest.locator('#feedback-form button[type=submit]').textContent(), 'Enviar avaliação');
  await guest.locator('#close-feedback-btn').click();
  assert.equal(await guest.locator('#open-feedback-btn').evaluate(node => node === document.activeElement), true);
  const deleteCard = admin.locator('.admin-review').filter({ hasText: 'Viajero con foto' });
  await deleteCard.waitFor();
  const deleteButton = deleteCard.getByRole('button', { name: 'Borrar', exact: true });
  await deleteButton.waitFor({ timeout: 5000 });
  admin.removeAllListeners('dialog');
  admin.once('dialog', async dialog => { assert.ok(dialog.message().includes('no se puede deshacer')); await dialog.dismiss(); });
  await deleteButton.click();
  assert.equal(await deleteCard.count(), 1, 'Cancel must preserve the review');
  assert.equal((await fetch(signed)).status, 200, 'Cancel must preserve its photo');
  admin.on('dialog', dialog => dialog.accept());
  await deleteButton.click();
  await admin.waitForFunction(() => !document.querySelector('#review-list').textContent.includes('Viajero con foto'));
  assert.equal((await fetch(signed)).status, 404, 'Permanent deletion must remove the actual photo file');
  await guest.reload({ waitUntil: 'domcontentloaded' });
  assert.equal(await guest.locator('.testimonial-author-name').filter({ hasText: 'Viajero con foto' }).count(), 0);
  await admin.locator('#status-filter').selectOption('hidden');
  const hiddenCard = admin.locator('.admin-review').filter({ hasText: 'Viajera de prueba' });
  await hiddenCard.waitFor();
  await hiddenCard.getByRole('button', { name: 'Borrar', exact: true }).click();
  await admin.waitForFunction(() => !document.querySelector('#review-list').textContent.includes('Viajera de prueba'));
  await admin.setViewportSize({ width: 390, height: 844 });
  assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await admin.screenshot({ path: join(directory, 'admin-mobile.png'), fullPage: true });
  const recovery = await browser.newPage();
  recovery.on('pageerror', error => errors.push(error.message));
  const session = await admin.evaluate(() => JSON.parse(sessionStorage.getItem('est-review-admin')));
  const fragment = new URLSearchParams({ access_token: session.access_token, refresh_token: session.refresh_token, expires_in: '3600', token_type: 'bearer', type: 'recovery' });
  await recovery.goto(preview.url + '/admin/#' + fragment, { waitUntil: 'domcontentloaded' });
  await recovery.locator('#password-section').waitFor({ state: 'visible' });
  assert.equal(await recovery.locator('#review-section').isVisible(), false, 'Recovery link must keep the password form open');
  const privacy = await browser.newPage({ viewport: { width: 390, height: 844 } });
  privacy.on('pageerror', error => errors.push(error.message));
  await privacy.route('**/*', route => new URL(route.request().url()).origin === preview.url ? route.continue() : route.abort());
  await privacy.goto(preview.url + '/privacy.html#review-privacy', { waitUntil: 'domcontentloaded' });
  assert.equal(await privacy.locator('#review-privacy-title').textContent(), 'Información sobre tus reseñas');
  await privacy.evaluate(() => window.__estI18n.setLang('en'));
  assert.equal(await privacy.locator('#review-privacy-title').textContent(), 'Information about your reviews');
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: guest submission, approval, XSS safety, photos, privacy, limits, hiding, permanent deletion and cancellation, translation, focus and mobile panel.');
} finally { await browser.close(); preview.server.closeAllConnections(); await new Promise(resolve => preview.server.close(resolve)); }
